apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector: { app: gateway }
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.gateway.port }}
